// -*- C++ -*-
/*
 * ****  Code generated by the RIDL Compiler ****
 * RIDL has been developed by:
 *        Remedy IT
 *        Nijkerk, GLD
 *        The Netherlands
 *        http://www.remedy.nl \ http://www.theaceorb.nl
 */

#ifndef __RIDL_TESTC_H_INCLUDED__
#define __RIDL_TESTC_H_INCLUDED__

#include <tao/0x/stddef.h>
#include <tao/0x/corba.h>

using namespace corba_0x;

// generated from StubHeaderWriter#enter_module
namespace Test {

  // generated from c++/cli_hdr/enum.erb
  enum class EEnum : uint32_t
  {
    A,
    B,
    C
  }; // EEnum

  // generated from StubHeaderWriter#visit_const
  constexpr EEnum my_enum = EEnum::A;
}; // namespace Test


// generated from StubHeaderStdWriter#pre_visit
namespace std {
}; // std

#include "TestC.inl"


#endif // __RIDL_TESTC_H_INCLUDED__

// -*- END -*-
