/*!
 * @file   test.idl
 * @author Johnny Willemsen <jwillemsen@remedy.nl>
 *
 * @brief  CORBA C++11 test idl
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */

/// Put the interfaces in a module, to avoid global namespace pollution
module Test
{
  struct Variable
  {
    string name;
  };

  interface Bar
  {
    void op ();
  };

  struct Simple
  {
    octet    o;
    long     l;
    string   s;
    double   d;
    boolean  b;
    char     c;
    Bar      bar_ref;
    Variable v;
  };

  /// A very simple interface
  interface Foo
  {
    boolean pass_struct (in Simple s);

    Simple return_struct ();

    boolean get_struct (out Simple s);

    boolean update_struct (inout Simple s);

    /// A method to shutdown the ORB
    /**
     * This method is used to simplify the test shutdown process
     */
    oneway void shutdown ();
  };
};
