// -*- C++ -*-
/*
 * ****  Code generated by the RIDL Compiler ****
 * RIDL has been developed by:
 *        Remedy IT
 *        Nijkerk, GLD
 *        The Netherlands
 *        http://www.remedy.nl \ http://www.theaceorb.nl
 */

#ifndef __RIDL_TESTS_H_DHIBJHJA_INCLUDED__
#define __RIDL_TESTS_H_DHIBJHJA_INCLUDED__

#include "testC.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/x11/portable_server/servantbase.h"


// generated from ServantHeaderWriter#enter_module
namespace Test
{
}; // namespace Test


// generated from ServantHeaderSrvTraitsWriter#pre_visit
namespace TAOX11_NAMESPACE {
  namespace CORBA {
  }; // CORBA
}; // TAOX11_NAMESPACE

#endif // __RIDL_TESTS_H_DHIBJHJA_INCLUDED__

// -*- END -*-
