/*!
 * @file   test.idl
 * @author Johnny Willemsen <jwillemsen@remedy.nl>
 *
 * @brief  CORBA C++11 test idl
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

struct ShapeType {
  string color; //@key
  long x;
  long y;
  long shapesize;
};

struct Attributes {
  string shape; //@key
  string color; //@key
  float speed;
};
typedef sequence<ShapeType> ShapeTypeSeq;

