// Put the interfaces in a module, to avoid global namespace pollution
module Test
{
  exception FooEx
  {
    string message;
  };

  exception BooEx
  {
    long id;    
  };

  /// A very simple interface
  interface Foo
  {
    void do_it () raises (FooEx);

    readonly attribute long a_number raises (BooEx);

    attribute string a_string setraises (FooEx, BooEx);

    /// A method to shutdown the ORB
    /**
     * This method is used to simplify the test shutdown process
     */
    oneway void shutdown ();
  };
};
