/*!
 * @file   test.idl
 * @author Johnny Willemsen <jwillemsen@remedy.nl>
 *
 * @brief  CORBA C++11 test idl
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */

/// Put the interfaces in a module, to avoid global namespace pollution
module Test
{
  typedef float F[10];
  typedef string V[10];
  typedef string M[1][2][3];

  interface Foo {
    void op(in F p1, out V p2, inout M p3);
  };
};
