struct ShapeType {
  string color; //@key
  long x;
  long y;
  long shapesize;
};

struct Attributes {
  string shape; //@key
  string color; //@key
  float speed;
};
typedef sequence<ShapeType> ShapeTypeSeq;

